version: "3.8"

services:
  backend:
    volumes:
      - ./src:/src:cached
    command: dotnet watch run --project MyBackend.Api/MyBackend.Api.csproj --urls http://0.0.0.0:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:5000"

  frontend:
    volumes:
      - ./web:/app:cached
    working_dir: /app
    command: npm start
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
